### ISSUE TITLE
Failed to activate the atom-pivottable package

### ISSUE THREAD

**Issue by brylie** [y-takey/atom-pivottable#1]
1. create a JSON file with example data
2. select all lines in JSON file
3. right click text
4. click "Pivot tableize"

**Atom Version**: 1.6.0
**System**: Ubuntu 15.10
**Thrown From**: [atom-pivottable](https://github.com/y-takey/atom-pivottable) package, v0.0.1
### Stack Trace

Failed to activate the atom-pivottable package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/brylie/.atom/packages/atom-pivottable/lib/atom-pivottable-view.coffee:5:10)
    at Object.<anonymous> (/home/brylie/.atom/packages/atom-pivottable/lib/atom-pivottable-view.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/brylie/.atom/packages/atom-pivottable/lib/atom-pivottable.coffee:2:38)
    at Object.<anonymous> (/home/brylie/.atom/packages/atom-pivottable/lib/atom-pivottable.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:172:16)
    at /usr/share/atom/resources/app.asar/src/package.js:800:25
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1019:28)
```
### Commands

```
     -0:02.9.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:00.7.0 atom-pivottable:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-gfm"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-pivottable, v0.0.1
language-markdown, v0.11.0
linter, v1.11.4
linter-eslint, v7.1.1
markdown-mindmap, v0.2.4
markdown-scroll-sync, v2.1.2
minimap, v4.21.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
tabs-to-spaces, v1.0.1
terminal-plus, v0.14.5
tidy-markdown, v2.0.0

# Dev
No dev packages
```

**Comment by brylie** [comment]
It looks like this package is missing the jQuery dependency.

**Comment by y-takey** [comment]
Dear @brylie ,

Thanks for your reporting! Sorry, I made a basic error. I've fixed the bug and published the atom package.(v0.0.2)
Please upgrade your atom-pivottable, then test again.
